apiVersion: v1
kind: Service
metadata:
  name: registry
spec:
  selector:
    app: registry
  ports:
  - name: "8761"
    port: 8761
    targetPort: 8761

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: registry
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
      - image: professionalprofile/registry
        name: registry
        env:
        - name: CONFIG_SERVICE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secrets
              key: CONFIG_SERVICE_PASSWORD
        ports:
        - containerPort: 8761
      restartPolicy: Always