export const EXPERIMENTS_FETCH_START = 'EXPERIMENTS_FETCH_START'
export const EXPERIMENTS_FETCH_SUCCESS = 'EXPERIMENTS_FETCH_SUCCESS'
export const EXPERIMENTS_FETCH_FAIL = 'EXPERIMENTS_FETCH_FAIL'

export const EXPERIMENT_SAVE_START = 'EXPERIMENT_SAVE_START'
export const EXPERIMENT_SAVE_SUCCESS = 'EXPERIMENT_SAVE_SUCCESS'
export const EXPERIMENT_SAVE_FAIL = 'EXPERIMENT_SAVE_FAIL'

export const EXPERIMENT_DELETE_START = 'EXPERIMENT_DELETE_START'
export const EXPERIMENT_DELETE_SUCCESS = 'EXPERIMENT_DELETE_SUCCESS'
export const EXPERIMENT_DELETE_FAIL = 'EXPERIMENT_DELETE_FAIL'