export const PROFILE_FETCH_START = 'PROFILE_FETCH_START'
export const PROFILE_FETCH_SUCCESS = 'PROFILE_FETCH_SUCCESS'
export const PROFILE_FETCH_FAIL = 'PROFILE_FETCH_FAIL'

export const PROFILE_SAVE_SUCCESS = 'PROFILE_SAVE_SUCCESS'
export const PROFILE_SAVE_START = 'PROFILE_SAVE_START'
export const PROFILE_SAVE_FAIL = 'PROFILE_SAVE_END'

export const PROFILE_DELETE_START = 'PROFILE_DELETE_START'
export const PROFILE_DELETE_SUCCESS = 'PROFILE_DELETE_SUCCESS'
export const PROFILE_DELETE_FAIL = 'PROFILE_DELETE_FAIL'