export const JOBS_FETCH_START = 'JOBS_FETCH_START'
export const JOBS_FETCH_SUCCESS = 'JOBS_FETCH_SUCCESS'
export const JOBS_FETCH_FAIL = 'JOBS_FETCH_FAIL'

export const JOB_SAVE_SUCCESS = 'JOB_SAVE_SUCCESS'
export const JOB_SAVE_START = 'JOB_SAVE_START'
export const JOB_SAVE_FAIL = 'JOB_SAVE_END'

export const JOB_DELETE_START = 'JOB_DELETE_START'
export const JOB_DELETE_SUCCESS = 'JOB_DELETE_SUCCESS'
export const JOB_DELETE_FAIL = 'JOB_DELETE_FAIL'