apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: skills-mongodb-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: skills-mongodb
spec:
  selector:
    matchLabels:
      app: skills-mongodb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: skills-mongodb
    spec:
      containers:
      - image: professionalprofile/mongodb
        name: skills-mongodb
        env:
        - name: MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secrets
              key: MONGODB_PASSWORD
        ports:
        - containerPort: 27017
          name: skills-mongodb
        volumeMounts:
        - name: mongodb-persistent-storage
          mountPath: /data/db
      volumes:
      - name: mongodb-persistent-storage
        persistentVolumeClaim:
          claimName: skills-mongodb-pv-claim

---
apiVersion: v1
kind: Service
metadata:
  name: skills-mongodb
spec:
  ports:
  - port: 27017
  selector:
    app: skills-mongodb
  clusterIP: None

---
apiVersion: v1
kind: Service
metadata:
  name: skills-service
spec:
  selector:
    app: skills-service
  ports:
  - port: 7000
  clusterIP: None

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: skills-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: skills-service
    spec:
      containers:
      - image: professionalprofile/skills-service
        name: skills-service
        env:
        - name: CONFIG_SERVICE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secrets
              key: CONFIG_SERVICE_PASSWORD
        - name: MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secrets
              key: MONGODB_PASSWORD
      restartPolicy: Always