export const SKILLS_FETCH_START = 'SKILLS_FETCH_START'
export const SKILLS_FETCH_SUCCESS = 'SKILLS_FETCH_SUCCESS'
export const SKILLS_FETCH_FAIL = 'SKILLS_FETCH_FAIL'

export const SKILL_SAVE_START = 'SKILL_SAVE_START'
export const SKILL_SAVE_SUCCESS = 'SKILL_SAVE_SUCCESS'
export const SKILL_SAVE_FAIL = 'SKILL_SAVE_FAIL'

export const SKILL_DELETE_START = 'SKILL_DELETE_START'
export const SKILL_DELETE_SUCCESS = 'SKILL_DELETE_SUCCESS'
export const SKILL_DELETE_FAIL = 'SKILL_DELETE_FAIL'