security:
  oauth2:
    client:
      clientId: skills-service
      clientSecret: ${SKILLS_SERVICE_PASSWORD}
      accessTokenUri: http://localhost:5000/uaa/oauth/token
      grant-type: client_credentials
      scope: server

spring:
  data:
    mongodb:
      host: localhost
      username: user
      password: ${MONGODB_PASSWORD}
      database: professional-profile
      port: 27017

server:
  context-path: /skills
  port: 7000
