apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: auth-mongodb-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: auth-mongodb
spec:
  selector:
    matchLabels:
      app: auth-mongodb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: auth-mongodb
    spec:
      containers:
      - image: professionalprofile/mongodb
        name: auth-mongodb
        env:
        - name: MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secrets
              key: MONGODB_PASSWORD
        ports:
        - containerPort: 27017
          name: auth-mongodb
        volumeMounts:
        - name: mongodb-persistent-storage
          mountPath: /data/db
      volumes:
      - name: mongodb-persistent-storage
        persistentVolumeClaim:
          claimName: auth-mongodb-pv-claim

---
apiVersion: v1
kind: Service
metadata:
  name: auth-mongodb
spec:
  ports:
  - port: 27017
  selector:
    app: auth-mongodb
  clusterIP: None

---  
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth-service
  ports:
  - port: 2000
  clusterIP: None

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - image: professionalprofile/auth-service
        name: auth-service
        env:
        - name: OWNER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secrets
              key: OWNER_PASSWORD        
        - name: CONFIG_SERVICE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secrets
              key: CONFIG_SERVICE_PASSWORD
        - name: MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secrets
              key: MONGODB_PASSWORD
      restartPolicy: Always