apiVersion: v1
kind: Service
metadata:
  name: config
spec:
  selector:
    app: config
  ports:
  - port: 8888
  clusterIP: None

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: config
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: config
    spec:
      containers:
      - image: leocavalcanti/professionalprofile_config
        name: config
        env:
        - name: CONFIG_SERVICE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secrets
              key: CONFIG_SERVICE_PASSWORD
      restartPolicy: Always