spring:
  data:
    mongodb:
      host: messages-mongodb
      username: user
      password: ${MONGODB_PASSWORD}
      database: professional-profile
      port: 27017

server:
  context-path: /messages
  port: 5000
