spring:
  data:
    mongodb:
      host: projects-mongodb
      username: user
      password: ${MONGODB_PASSWORD}
      database: professional-profile
      port: 27017

server:
  context-path: /projects
  port: 8000
