apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: projects-mongodb-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: projects-mongodb
spec:
  selector:
    matchLabels:
      app: projects-mongodb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: projects-mongodb
    spec:
      containers:
      - image: professionalprofile/mongodb
        name: projects-mongodb
        env:
        - name: MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secrets
              key: MONGODB_PASSWORD
        ports:
        - containerPort: 27017
          name: projects-mongodb
        volumeMounts:
        - name: mongodb-persistent-storage
          mountPath: /data/db
      volumes:
      - name: mongodb-persistent-storage
        persistentVolumeClaim:
          claimName: projects-mongodb-pv-claim

---
apiVersion: v1
kind: Service
metadata:
  name: projects-mongodb
spec:
  ports:
  - port: 27017
  selector:
    app: projects-mongodb
  clusterIP: None

---
apiVersion: v1
kind: Service
metadata:
  name: projects-service
spec:
  selector:
    app: projects-service
  ports:
  - port: 8000
  clusterIP: None

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: projects-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: projects-service
    spec:
      containers:
      - image: professionalprofile/projects-service
        name: projects-service
        env:
        - name: CONFIG_SERVICE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secrets
              key: CONFIG_SERVICE_PASSWORD
        - name: MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secrets
              key: MONGODB_PASSWORD
        - name: RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secrets
              key: RABBITMQ_PASSWORD
      restartPolicy: Always